// Disease mapping from numeric index to disease name
const DISEASE_MAP = {
  0: 'abdominal aortic aneurysm',
  1: 'abdominal hernia',
  2: 'abscess of nose',
  3: 'abscess of the lung',
  4: 'abscess of the pharynx',
  5: 'acanthosis nigricans',
  6: 'acariasis',
  7: 'achalasia',
  8: 'acne',
  9: 'actinic keratosis',
  10: 'acute bronchiolitis',
  11: 'acute bronchitis',
  12: 'acute bronchospasm',
  13: 'acute fatty liver of pregnancy (aflp)',
  14: 'acute glaucoma',
  15: 'acute kidney injury',
  16: 'acute otitis media',
  17: 'acute pancreatitis',
  18: 'acute respiratory distress syndrome (ards)',
  19: 'acute sinusitis',
  20: 'acute stress reaction',
  21: 'adhesive capsulitis of the shoulder',
  22: 'adjustment reaction',
  23: 'adrenal adenoma',
  24: 'adrenal cancer',
  25: 'alcohol abuse',
  26: 'alcohol intoxication',
  27: 'alcohol withdrawal',
  28: 'alcoholic liver disease',
  29: 'allergy',
  30: 'allergy to animals',
  31: 'alopecia',
  32: 'alzheimer disease',
  33: 'amblyopia',
  34: 'amyloidosis',
  35: 'amyotrophic lateral sclerosis (als)',
  36: 'anal fissure',
  37: 'anal fistula',
  38: 'anemia',
  39: 'anemia due to chronic kidney disease',
  40: 'anemia due to malignancy',
  41: 'anemia of chronic disease',
  42: 'angina',
  43: 'ankylosing spondylitis',
  44: 'anxiety',
  45: 'aortic valve disease',
  46: 'aphakia',
  47: 'aphthous ulcer',
  48: 'aplastic anemia',
  49: 'appendicitis',
  50: 'arrhythmia',
  51: 'arthritis of the hip',
  52: 'ascending cholangitis',
  53: 'asperger syndrome',
  54: 'aspergillosis',
  55: 'asthma',
  56: 'astigmatism',
  57: 'atelectasis',
  58: "athlete's foot",
  59: 'atonic bladder',
  60: 'atrial fibrillation',
  61: 'atrial flutter',
  62: 'atrophic skin condition',
  63: 'atrophic vaginitis',
  64: 'atrophy of the corpus cavernosum',
  65: 'attention deficit hyperactivity disorder (adhd)',
  66: 'autism',
  67: 'autonomic nervous system disorder',
  68: 'avascular necrosis',
  69: 'balanitis',
  70: 'bell palsy',
  71: 'benign kidney cyst',
  72: 'benign paroxysmal positional vertical (bppv)',
  73: 'benign prostatic hyperplasia (bph)',
  74: 'benign vaginal discharge (leukorrhea)',
  75: 'bipolar disorder',
  76: 'birth trauma',
  77: 'bladder cancer',
  78: 'bladder disorder',
  79: 'bladder obstruction',
  80: 'blepharitis',
  81: 'blepharospasm',
  82: 'bone cancer',
  83: 'bone disorder',
  84: 'bone spur of the calcaneous',
  85: 'brachial neuritis',
  86: 'brain cancer',
  87: 'breast cancer',
  88: 'breast cyst',
  89: 'breast infection (mastitis)',
  90: 'broken tooth',
  91: 'bunion',
  92: 'burn',
  93: 'bursitis',
  94: 'callus',
  95: 'carbon monoxide poisoning',
  96: 'carcinoid syndrome',
  97: 'cardiac arrest',
  98: 'cardiomyopathy',
  99: 'carpal tunnel syndrome',
  100: 'cat scratch disease',
  101: 'cataract',
  102: 'celiac disease',
  103: 'cellulitis or abscess of mouth',
  104: 'central atherosclerosis',
  105: 'central retinal artery or vein occlusion',
  106: 'cerebral edema',
  107: 'cerebral palsy',
  108: 'cervical cancer',
  109: 'cervical disorder',
  110: 'cervicitis',
  111: 'chalazion',
  112: 'chickenpox',
  113: 'chlamydia',
  114: 'cholecystitis',
  115: 'choledocholithiasis',
  116: 'cholesteatoma',
  117: 'chondromalacia of the patella',
  118: 'chorioretinitis',
  119: 'chronic back pain',
  120: 'chronic constipation',
  121: 'chronic glaucoma',
  122: 'chronic inflammatory demyelinating polyneuropathy (cidp)',
  123: 'chronic kidney disease',
  124: 'chronic knee pain',
  125: 'chronic obstructive pulmonary disease (copd)',
  126: 'chronic otitis media',
  127: 'chronic pain disorder',
  128: 'chronic pancreatitis',
  129: 'chronic rheumatic fever',
  130: 'chronic sinusitis',
  131: 'chronic ulcer',
  132: 'cirrhosis',
  133: 'coagulation (bleeding) disorder',
  134: 'cold sore',
  135: 'colonic polyp',
  136: 'colorectal cancer',
  137: 'common cold',
  138: 'complex regional pain syndrome',
  139: 'concussion',
  140: 'conduct disorder',
  141: 'conductive hearing loss',
  142: 'congenital heart defect',
  143: 'congenital malformation syndrome',
  144: 'conjunctivitis',
  145: 'conjunctivitis due to allergy',
  146: 'conjunctivitis due to bacteria',
  147: 'conjunctivitis due to virus',
  148: 'connective tissue disorder',
  149: 'contact dermatitis',
  150: 'conversion disorder',
  151: 'cornea infection',
  152: 'corneal abrasion',
  153: 'corneal disorder',
  154: 'coronary atherosclerosis',
  155: 'cranial nerve palsy',
  156: 'crohn disease',
  157: 'croup',
  158: 'crushing injury',
  159: 'cryptococcosis',
  160: 'cryptorchidism',
  161: 'cushing syndrome',
  162: 'cyst of the eyelid',
  163: 'cystic fibrosis',
  164: 'cysticercosis',
  165: 'cystitis',
  166: 'de quervain disease',
  167: 'decubitus ulcer',
  168: 'deep vein thrombosis (dvt)',
  169: 'degenerative disc disease',
  170: 'delirium',
  171: 'dementia',
  172: 'dengue fever',
  173: 'dental caries',
  174: 'depression',
  175: 'dermatitis due to sun exposure',
  176: 'developmental disability',
  177: 'deviated nasal septum',
  178: 'diabetes',
  179: 'diabetes insipidus',
  180: 'diabetic ketoacidosis',
  181: 'diabetic kidney disease',
  182: 'diabetic peripheral neuropathy',
  183: 'diabetic retinopathy',
  184: 'diaper rash',
  185: 'dislocation of the ankle',
  186: 'dislocation of the elbow',
  187: 'dislocation of the finger',
  188: 'dislocation of the foot',
  189: 'dislocation of the hip',
  190: 'dislocation of the knee',
  191: 'dislocation of the patella',
  192: 'dislocation of the shoulder',
  193: 'dislocation of the vertebra',
  194: 'dislocation of the wrist',
  195: 'dissociative disorder',
  196: 'diverticulitis',
  197: 'diverticulosis',
  198: 'down syndrome',
  199: 'drug abuse'
};

module.exports = DISEASE_MAP; 