// Map of disease indices to disease names
const DISEASE_MAP = {
  0: 'Abdominal Aortic Aneurysm',
  1: 'Abdominal Hernia',
  2: 'Abscess of Nose',
  3: 'Abscess of the Lung',
  4: 'Abscess of the Pharynx',
  5: 'Acanthosis Nigricans',
  6: 'Acariasis',
  7: 'Achalasia',
  8: 'Acne',
  9: 'Actinic Keratosis',
  10: 'Acute Bronchiolitis',
  11: 'Acute Bronchitis',
  12: 'Acute Bronchospasm',
  13: 'Acute Fatty Liver of Pregnancy (AFLP)',
  14: 'Acute Glaucoma',
  15: 'Acute Kidney Injury',
  16: 'Acute Otitis Media',
  17: 'Acute Pancreatitis',
  18: 'Acute Respiratory Distress Syndrome (ARDS)',
  19: 'Acute Sinusitis',
  20: 'Acute Stress Reaction',
  21: 'Adhesive Capsulitis of the Shoulder',
  22: 'Adjustment Reaction',
  23: 'Adrenal Adenoma',
  24: 'Adrenal Cancer',
  25: 'Alcohol Abuse',
  26: 'Alcohol Intoxication',
  27: 'Alcohol Withdrawal',
  28: 'Alcoholic Liver Disease',
  29: 'Allergy',
  30: 'Allergy to Animals',
  31: 'Alopecia',
  32: 'Alzheimer Disease',
  33: 'Amblyopia',
  34: 'Amyloidosis',
  35: 'Amyotrophic Lateral Sclerosis (ALS)',
  36: 'Anal Fissure',
  37: 'Anal Fistula',
  38: 'Anemia',
  39: 'Anemia Due to Chronic Kidney Disease',
  40: 'Anemia Due to Malignancy',
  41: 'Anemia of Chronic Disease',
  42: 'Angina',
  43: 'Ankylosing Spondylitis',
  44: 'Anxiety',
  45: 'Aortic Valve Disease',
  46: 'Aphakia',
  47: 'Aphthous Ulcer',
  48: 'Aplastic Anemia',
  49: 'Appendicitis',
  50: 'Arrhythmia',
  51: 'Arthritis of the Hip',
  52: 'Ascending Cholangitis',
  53: 'Asperger Syndrome',
  54: 'Aspergillosis',
  55: 'Asthma',
  56: 'Astigmatism',
  57: 'Atelectasis',
  58: "Athlete's Foot",
  59: 'Atonic Bladder',
  60: 'Atrial Fibrillation',
  61: 'Atrial Flutter',
  62: 'Atrophic Skin Condition',
  63: 'Atrophic Vaginitis',
  64: 'Atrophy of the Corpus Cavernosum',
  65: 'Attention Deficit Hyperactivity Disorder (ADHD)',
  66: 'Autism',
  67: 'Autonomic Nervous System Disorder',
  68: 'Avascular Necrosis',
  69: 'Balanitis',
  70: 'Bell Palsy',
  71: 'Benign Kidney Cyst',
  72: 'Benign Paroxysmal Positional Vertical (BPPV)',
  73: 'Benign Prostatic Hyperplasia (BPH)',
  74: 'Benign Vaginal Discharge (Leukorrhea)',
  75: 'Bipolar Disorder',
  76: 'Birth Trauma',
  77: 'Bladder Cancer',
  78: 'Bladder Disorder',
  79: 'Bladder Obstruction',
  80: 'Blepharitis',
  81: 'Blepharospasm',
  82: 'Bone Cancer',
  83: 'Bone Disorder',
  84: 'Bone Spur of the Calcaneous',
  85: 'Brachial Neuritis',
  86: 'Brain Cancer',
  87: 'Breast Cancer',
  88: 'Breast Cyst',
  89: 'Breast Infection (Mastitis)',
  90: 'Broken Tooth',
  91: 'Bunion',
  92: 'Burn',
  93: 'Bursitis',
  94: 'Callus',
  95: 'Carbon Monoxide Poisoning',
  96: 'Carcinoid Syndrome',
  97: 'Cardiac Arrest',
  98: 'Cardiomyopathy',
  99: 'Carpal Tunnel Syndrome',
  100: 'Cat Scratch Disease',
  101: 'Cataract',
  102: 'Celiac Disease',
  103: 'Cellulitis or Abscess of Mouth',
  104: 'Central Atherosclerosis',
  105: 'Central Retinal Artery or Vein Occlusion',
  106: 'Cerebral Edema',
  107: 'Cerebral Palsy',
  108: 'Cervical Cancer',
  109: 'Cervical Disorder',
  110: 'Cervicitis',
  111: 'Chalazion',
  112: 'Chickenpox',
  113: 'Chlamydia',
  114: 'Cholecystitis',
  115: 'Choledocholithiasis',
  116: 'Cholesteatoma',
  117: 'Chondromalacia of the Patella',
  118: 'Chorioretinitis',
  119: 'Chronic Back Pain',
  120: 'Chronic Constipation',
  121: 'Chronic Glaucoma',
  122: 'Chronic Inflammatory Demyelinating Polyneuropathy (CIDP)',
  123: 'Chronic Kidney Disease',
  124: 'Chronic Knee Pain',
  125: 'Chronic Obstructive Pulmonary Disease (COPD)',
  126: 'Chronic Otitis Media',
  127: 'Chronic Pain Disorder',
  128: 'Chronic Pancreatitis',
  129: 'Chronic Rheumatic Fever',
  130: 'Chronic Sinusitis',
  131: 'Chronic Ulcer',
  132: 'Cirrhosis',
  133: 'Coagulation (Bleeding) Disorder',
  134: 'Cold Sore',
  135: 'Colonic Polyp',
  136: 'Colorectal Cancer',
  137: 'Common Cold',
  138: 'Complex Regional Pain Syndrome',
  139: 'Concussion',
  140: 'Conduct Disorder',
  141: 'Conductive Hearing Loss',
  142: 'Congenital Heart Defect',
  143: 'Congenital Malformation Syndrome',
  144: 'Conjunctivitis',
  145: 'Conjunctivitis Due to Allergy',
  146: 'Conjunctivitis Due to Bacteria',
  147: 'Conjunctivitis Due to Virus',
  148: 'Connective Tissue Disorder',
  149: 'Contact Dermatitis',
  150: 'Conversion Disorder',
  151: 'Cornea Infection',
  152: 'Corneal Abrasion',
  153: 'Corneal Disorder',
  154: 'Coronary Atherosclerosis',
  155: 'Cranial Nerve Palsy',
  156: 'Crohn Disease',
  157: 'Croup',
  158: 'Crushing Injury',
  159: 'Cryptococcosis',
  160: 'Cryptorchidism',
  161: 'Cushing Syndrome',
  162: 'Cyst of the Eyelid',
  163: 'Cystic Fibrosis',
  164: 'Cysticercosis',
  165: 'Cystitis',
  166: 'De Quervain Disease',
  167: 'Decubitus Ulcer',
  168: 'Deep Vein Thrombosis (DVT)',
  169: 'Degenerative Disc Disease',
  170: 'Delirium',
  171: 'Dementia',
  172: 'Dengue Fever',
  173: 'Dental Caries',
  174: 'Depression',
  175: 'Dermatitis Due to Sun Exposure',
  176: 'Developmental Disability',
  177: 'Deviated Nasal Septum',
  178: 'Diabetes',
  179: 'Diabetes Insipidus',
  180: 'Diabetic Ketoacidosis',
  181: 'Diabetic Kidney Disease',
  182: 'Diabetic Peripheral Neuropathy',
  183: 'Diabetic Retinopathy',
  184: 'Diaper Rash',
  185: 'Dislocation of the Ankle',
  186: 'Dislocation of the Elbow',
  187: 'Dislocation of the Finger',
  188: 'Dislocation of the Foot',
  189: 'Dislocation of the Hip',
  190: 'Dislocation of the Knee',
  191: 'Dislocation of the Patella',
  192: 'Dislocation of the Shoulder',
  193: 'Dislocation of the Vertebra',
  194: 'Dislocation of the Wrist',
  195: 'Dissociative Disorder',
  196: 'Diverticulitis',
  197: 'Diverticulosis',
  198: 'Down Syndrome',
  199: 'Drug Abuse',
  200: 'Drug Abuse (Barbiturates)',
  201: 'Drug Abuse (Cocaine)',
  202: 'Drug Abuse (Methamphetamine)',
  203: 'Drug Abuse (Opioids)',
  204: 'Drug Poisoning Due to Medication',
  205: 'Drug Reaction',
  206: 'Drug Withdrawal',
  207: 'Dry Eye of Unknown Cause',
  208: 'Dumping Syndrome',
  209: 'Dyshidrosis',
  210: 'Dysthymic Disorder',
  211: 'Ear Drum Damage',
  212: 'Ear Wax Impaction',
  213: 'Eating Disorder',
  214: 'Ectopic Pregnancy',
  215: 'Ectropion',
  216: 'Eczema',
  217: 'Edward Syndrome',
  218: 'Emphysema',
  219: 'Empyema',
  220: 'Encephalitis',
  221: 'Endocarditis',
  222: 'Endometrial Cancer',
  223: 'Endometrial Hyperplasia',
  224: 'Endometriosis',
  225: 'Endophthalmitis',
  226: 'Envenomation from Spider or Animal Bite',
  227: 'Ependymoma',
  228: 'Epididymitis',
  229: 'Epidural Hemorrhage',
  230: 'Epilepsy',
  231: 'Erectile Dysfunction',
  232: 'Erythema Multiforme',
  233: 'Esophageal Cancer',
  234: 'Esophageal Varices',
  235: 'Esophagitis',
  236: 'Essential Tremor',
  237: 'Eustachian Tube Dysfunction (Ear Disorder)',
  238: 'Extrapyramidal Effect of Drugs',
  239: 'Eye Alignment Disorder',
  240: 'Factitious Disorder',
  241: 'Female Genitalia Infection',
  242: 'Female Infertility of Unknown Cause',
  243: 'Fetal Alcohol Syndrome',
  244: 'Fibroadenoma',
  245: 'Fibrocystic Breast Disease',
  246: 'Fibromyalgia',
  247: 'Flat Feet',
  248: 'Floaters',
  249: 'Flu',
  250: 'Fluid Overload',
  251: 'Folate Deficiency',
  252: 'Food Allergy',
  253: 'Foreign Body in the Ear',
  254: 'Foreign Body in the Eye',
  255: 'Foreign Body in the Gastrointestinal Tract',
  256: 'Foreign Body in the Nose',
  257: 'Foreign Body in the Throat',
  258: 'Foreign Body in the Vagina',
  259: 'Fracture of the Ankle',
  260: 'Fracture of the Arm',
  261: 'Fracture of the Facial Bones',
  262: 'Fracture of the Finger',
  263: 'Fracture of the Foot',
  264: 'Fracture of the Hand',
  265: 'Fracture of the Jaw',
  266: 'Fracture of the Leg',
  267: 'Fracture of the Neck',
  268: 'Fracture of the Patella',
  269: 'Fracture of the Pelvis',
  270: 'Fracture of the Rib',
  271: 'Fracture of the Shoulder',
  272: 'Fracture of the Skull',
  273: 'Fracture of the Vertebra',
  274: 'Friedrich Ataxia',
  275: 'Frostbite',
  276: 'Fungal Infection of the Hair',
  277: 'Fungal Infection of the Skin',
  278: 'G6PD Enzyme Deficiency',
  279: 'Galactorrhea of Unknown Cause',
  280: 'Gallstone',
  281: 'Ganglion Cyst',
  282: 'Gas Gangrene',
  283: 'Gastritis',
  284: 'Gastroduodenal Ulcer',
  285: 'Gastroesophageal Reflux Disease (GERD)',
  286: 'Gastrointestinal Hemorrhage',
  287: 'Gastroparesis',
  288: 'Genital Herpes',
  289: 'Gestational Diabetes',
  290: 'Glaucoma',
  291: 'Glucocorticoid Deficiency',
  292: 'Goiter',
  293: 'Gonorrhea',
  294: 'Gout',
  295: 'Granuloma Inguinale',
  296: 'Graves Disease',
  297: 'Guillain Barre Syndrome',
  298: 'Gum Disease',
  299: 'Gynecomastia',
  300: 'Hammer Toe',
  301: 'Hashimoto Thyroiditis',
  302: 'Head and Neck Cancer',
  303: 'Head Injury',
  304: 'Headache After Lumbar Puncture',
  305: 'Heart Attack',
  306: 'Heart Block',
  307: 'Heart Contusion',
  308: 'Heart Failure',
  309: 'Heat Exhaustion',
  310: 'Heat Stroke',
  311: 'Hemangioma',
  312: 'Hemarthrosis',
  313: 'Hematoma',
  314: 'Hemiplegia',
  315: 'Hemochromatosis',
  316: 'Hemolytic Anemia',
  317: 'Hemophilia',
  318: 'Hemorrhoids',
  319: 'Hepatic Encephalopathy',
  320: 'Hepatitis Due to a Toxin',
  321: 'Herniated Disk',
  322: 'Herpangina',
  323: 'Hiatal Hernia',
  324: 'Hidradenitis Suppurativa',
  325: 'High Blood Pressure',
  326: 'Hirschsprung Disease',
  327: 'Hirsutism',
  328: 'Histoplasmosis',
  329: 'Hormone Disorder',
  330: 'HPV',
  331: 'Human Immunodeficiency Virus Infection (HIV)',
  332: 'Huntington Disease',
  333: 'Hydatidiform Mole',
  334: 'Hydrocele of the Testicle',
  335: 'Hydrocephalus',
  336: 'Hydronephrosis',
  337: 'Hypercalcemia',
  338: 'Hypercholesterolemia',
  339: 'Hyperemesis Gravidarum',
  340: 'Hypergammaglobulinemia',
  341: 'Hyperhidrosis',
  342: 'Hyperkalemia',
  343: 'Hyperlipidemia',
  344: 'Hypernatremia',
  345: 'Hyperopia',
  346: 'Hyperosmotic Hyperketotic State',
  347: 'Hypertension of Pregnancy',
  348: 'Hypertensive Heart Disease',
  349: 'Hypertrophic Obstructive Cardiomyopathy (HOCM)',
  350: 'Hypocalcemia',
  351: 'Hypoglycemia',
  352: 'Hypokalemia',
  353: 'Hyponatremia',
  354: 'Hypothermia',
  355: 'Hypothyroidism',
  356: 'Hypovolemia',
  357: 'Idiopathic Absence of Menstruation',
  358: 'Idiopathic Excessive Menstruation',
  359: 'Idiopathic Infrequent Menstruation',
  360: 'Idiopathic Irregular Menstrual Cycle',
  361: 'Idiopathic Nonmenstrual Bleeding',
  362: 'Idiopathic Painful Menstruation',
  363: 'Ileus',
  364: 'Impetigo',
  365: 'Impulse Control Disorder',
  366: 'Indigestion',
  367: 'Induced Abortion',
  368: 'Infection of Open Wound',
  369: 'Infectious Gastroenteritis',
  370: 'Ingrown Toe Nail',
  371: 'Inguinal Hernia',
  372: 'Injury of the Ankle',
  373: 'Injury to Internal Organ',
  374: 'Injury to the Abdomen',
  375: 'Injury to the Arm',
  376: 'Injury to the Face',
  377: 'Injury to the Finger',
  378: 'Injury to the Hand',
  379: 'Injury to the Hip',
  380: 'Injury to the Knee',
  381: 'Injury to the Leg',
  382: 'Injury to the Shoulder',
  383: 'Injury to the Spinal Cord',
  384: 'Injury to the Trunk',
  385: 'Insect Bite',
  386: 'Insulin Overdose',
  387: 'Interstitial Lung Disease',
  388: 'Intertrigo (Skin Condition)',
  389: 'Intestinal Cancer',
  390: 'Intestinal Disease',
  391: 'Intestinal Malabsorption',
  392: 'Intestinal Obstruction',
  393: 'Intracerebral Hemorrhage',
  394: 'Intracranial Abscess',
  395: 'Intracranial Hemorrhage',
  396: 'Intussusception',
  397: 'Iridocyclitis',
  398: 'Iron Deficiency Anemia',
  399: 'Irritable Bowel Syndrome',
  400: 'Ischemia of the Bowel',
  401: 'Ischemic Heart Disease',
  402: 'Itching of Unknown Cause',
  403: 'Jaw Disorder',
  404: 'Joint Effusion',
  405: 'Juvenile Rheumatoid Arthritis',
  406: 'Kaposi Sarcoma',
  407: 'Kidney Cancer',
  408: 'Kidney Disease Due to Longstanding Hypertension',
  409: 'Kidney Failure',
  410: 'Kidney Stone',
  411: 'Knee Ligament or Meniscus Tear',
  412: 'Labyrinthitis',
  413: 'Lactose Intolerance',
  414: 'Laryngitis',
  415: 'Lateral Epicondylitis (Tennis Elbow)',
  416: 'Leukemia',
  417: 'Lewy Body Dementia',
  418: 'Lice',
  419: 'Lichen Planus',
  420: 'Lichen Simplex',
  421: 'Lipoma',
  422: 'Liver Cancer',
  423: 'Liver Disease',
  424: 'Lumbago',
  425: 'Lung Cancer',
  426: 'Lung Contusion',
  427: 'Lyme Disease',
  428: 'Lymphadenitis',
  429: 'Lymphangitis',
  430: 'Lymphedema',
  431: 'Lymphogranuloma Venereum',
  432: 'Lymphoma',
  433: 'Macular Degeneration',
  434: 'Magnesium Deficiency',
  435: 'Malaria',
  436: 'Male Genitalia Infection',
  437: 'Malignant Hypertension',
  438: 'Marijuana Abuse',
  439: 'Mastectomy',
  440: 'Mastoiditis',
  441: 'Meckel Diverticulum',
  442: 'Melanoma',
  443: 'Meniere Disease',
  444: 'Meningioma',
  445: 'Meningitis',
  446: 'Menopause',
  447: 'Metabolic Disorder',
  448: 'Metastatic Cancer',
  449: 'Migraine',
  450: 'Missed Abortion',
  451: 'Mitral Valve Disease',
  452: 'Mittelschmerz',
  453: 'Molluscum Contagiosum',
  454: 'Mononeuritis',
  455: 'Mononucleosis',
  456: 'Moyamoya Disease',
  457: 'Mucositis',
  458: 'Multiple Myeloma',
  459: 'Multiple Sclerosis',
  460: 'Mumps',
  461: 'Muscle Spasm',
  462: 'Muscular Dystrophy',
  463: 'Myasthenia Gravis',
  464: 'Myelodysplastic Syndrome',
  465: 'Myocarditis',
  466: 'Myoclonus',
  467: 'Myopia',
  468: 'Myositis',
  469: 'Narcolepsy',
  470: 'Nasal Polyp',
  471: 'Necrotizing Fasciitis',
  472: 'Neonatal Jaundice',
  473: 'Nerve Impingement Near the Shoulder',
  474: 'Neuralgia',
  475: 'Neurofibromatosis',
  476: 'Neuropathy Due to Drugs',
  477: 'Neurosis',
  478: 'Nonalcoholic Liver Disease (NASH)',
  479: 'Noninfectious Gastroenteritis',
  480: 'Normal Pressure Hydrocephalus',
  481: 'Nose Disorder',
  482: 'Obesity',
  483: 'Obsessive Compulsive Disorder (OCD)',
  484: 'Obstructive Sleep Apnea (OSA)',
  485: 'Omphalitis',
  486: 'Onychomycosis',
  487: 'Open Wound Due to Trauma',
  488: 'Open Wound from Surgical Incision',
  489: 'Open Wound of the Abdomen',
  490: 'Open Wound of the Arm',
  491: 'Open Wound of the Back',
  492: 'Open Wound of the Cheek',
  493: 'Open Wound of the Chest',
  494: 'Open Wound of the Ear',
  495: 'Open Wound of the Eye',
  496: 'Open Wound of the Face',
  497: 'Open Wound of the Finger',
  498: 'Open Wound of the Foot',
  499: 'Open Wound of the Hand',
  500: 'Open Wound of the Head',
  501: 'Open Wound of the Jaw',
  502: 'Open Wound of the Knee',
  503: 'Open Wound of the Lip',
  504: 'Open Wound of the Mouth',
  505: 'Open Wound of the Neck',
  506: 'Open Wound of the Nose',
  507: 'Open Wound of the Shoulder',
  508: 'Oppositional Disorder',
  509: 'Optic Neuritis',
  510: 'Oral Leukoplakia',
  511: 'Oral Mucosal Lesion',
  512: 'Oral Thrush (Yeast Infection)',
  513: 'Orbital Cellulitis',
  514: 'Orthostatic Hypotension',
  515: 'Osteoarthritis',
  516: 'Osteochondroma',
  517: 'Osteochondrosis',
  518: 'Osteomyelitis',
  519: 'Osteoporosis',
  520: "Otitis Externa (Swimmer's Ear)",
  521: 'Otitis Media',
  522: 'Otosclerosis',
  523: 'Ovarian Cancer',
  524: 'Ovarian Cyst',
  525: 'Ovarian Torsion',
  526: 'Overflow Incontinence',
  527: 'Pain After an Operation',
  528: 'Pain Disorder Affecting the Neck',
  529: 'Pancreatic Cancer',
  530: 'Panic Attack',
  531: 'Panic Disorder',
  532: 'Parasitic Disease',
  533: 'Parathyroid Adenoma',
  534: 'Parkinson Disease',
  535: 'Paronychia',
  536: 'Paroxysmal Supraventricular Tachycardia',
  537: 'Paroxysmal Ventricular Tachycardia',
  538: 'Pelvic Fistula',
  539: 'Pelvic Inflammatory Disease',
  540: 'Pelvic Organ Prolapse',
  541: 'Pemphigus',
  542: 'Pericarditis',
  543: 'Peripheral Arterial Disease',
  544: 'Peripheral Arterial Embolism',
  545: 'Peripheral Nerve Disorder',
  546: 'Perirectal Infection',
  547: 'Peritonitis',
  548: 'Peritonsillar Abscess',
  549: 'Persistent Vomiting of Unknown Cause',
  550: 'Personality Disorder',
  551: 'Peyronie Disease',
  552: 'Pharyngitis',
  553: 'Phimosis',
  554: 'Pilonidal Cyst',
  555: 'Pinguecula',
  556: 'Pinworm Infection',
  557: 'Pituitary Adenoma',
  558: 'Pituitary Disorder',
  559: 'Pityriasis Rosea',
  560: 'Placenta Previa',
  561: 'Placental Abruption',
  562: 'Plantar Fasciitis',
  563: 'Pleural Effusion',
  564: 'Pneumoconiosis',
  565: 'Pneumonia',
  566: 'Pneumothorax',
  567: 'Poisoning Due to Analgesics',
  568: 'Poisoning Due to Anticonvulsants',
  569: 'Poisoning Due to Antidepressants',
  570: 'Poisoning Due to Antihypertensives',
  571: 'Poisoning Due to Antimicrobial Drugs',
  572: 'Poisoning Due to Antipsychotics',
  573: 'Poisoning Due to Ethylene Glycol',
  574: 'Poisoning Due to Gas',
  575: 'Poisoning Due to Opioids',
  576: 'Poisoning Due to Sedatives',
  577: 'Polycystic Kidney Disease',
  578: 'Polycystic Ovarian Syndrome (PCOS)',
  579: 'Polycythemia Vera',
  580: 'Polymyalgia Rheumatica',
  581: 'Post-Traumatic Stress Disorder (PTSD)',
  582: 'Postoperative Infection',
  583: 'Postpartum Depression',
  584: 'Preeclampsia',
  585: 'Pregnancy',
  586: 'Premature Atrial Contractions (PACs)',
  587: 'Premature Ovarian Failure',
  588: 'Premature Rupture of Amniotic Membrane',
  589: 'Premature Ventricular Contractions (PVCs)',
  590: 'Premenstrual Tension Syndrome',
  591: 'Presbyacusis',
  592: 'Presbyopia',
  593: 'Priapism',
  594: 'Primary Immunodeficiency',
  595: 'Primary Insomnia',
  596: 'Primary Kidney Disease',
  597: 'Primary Thrombocythemia',
  598: 'Problem During Pregnancy',
  599: 'Prostate Cancer',
  600: 'Prostatitis',
  601: 'Protein Deficiency',
  602: 'Pseudohypoparathyroidism',
  603: 'Pseudotumor Cerebri',
  604: 'Psoriasis',
  605: 'Psychosexual Disorder',
  606: 'Psychotic Disorder',
  607: 'Pterygium',
  608: 'Pulmonary Congestion',
  609: 'Pulmonary Embolism',
  610: 'Pulmonary Eosinophilia',
  611: 'Pulmonary Fibrosis',
  612: 'Pulmonary Hypertension',
  613: 'Pulmonic Valve Disease',
  614: 'Pyelonephritis',
  615: 'Pyloric Stenosis',
  616: 'Pyogenic Skin Infection',
  617: 'Raynaud Disease',
  618: 'Reactive Arthritis',
  619: 'Rectal Disorder',
  620: 'Restless Leg Syndrome',
  621: 'Retinal Detachment',
  622: 'Retinopathy Due to High Blood Pressure',
  623: 'Rhabdomyolysis',
  624: 'Rheumatic Fever',
  625: 'Rheumatoid Arthritis',
  626: 'Rocky Mountain Spotted Fever',
  627: 'Rosacea',
  628: 'Rotator Cuff Injury',
  629: 'Salivary Gland Disorder',
  630: 'Sarcoidosis',
  631: 'Scabies',
  632: 'Scar',
  633: 'Scarlet Fever',
  634: 'Schizophrenia',
  635: 'Sciatica',
  636: 'Scleritis',
  637: 'Scleroderma',
  638: 'Scoliosis',
  639: 'Scurvy',
  640: 'Seasonal Allergies (Hay Fever)',
  641: 'Sebaceous Cyst',
  642: 'Seborrheic Dermatitis',
  643: 'Seborrheic Keratosis',
  644: 'Sensorineural Hearing Loss',
  645: 'Sepsis',
  646: 'Septic Arthritis',
  647: 'Shingles (Herpes Zoster)',
  648: 'Sialoadenitis',
  649: 'Sick Sinus Syndrome',
  650: 'Sickle Cell Anemia',
  651: 'Sickle Cell Crisis',
  652: 'Sinus Bradycardia',
  653: 'Sjogren Syndrome',
  654: 'Skin Cancer',
  655: 'Skin Disorder',
  656: 'Skin Pigmentation Disorder',
  657: 'Skin Polyp',
  658: 'Smoking or Tobacco Addiction',
  659: 'Social Phobia',
  660: 'Soft Tissue Sarcoma',
  661: 'Somatization Disorder',
  662: 'Spermatocele',
  663: 'Spherocytosis',
  664: 'Spina Bifida',
  665: 'Spinal Stenosis',
  666: 'Spinocerebellar Ataxia',
  667: 'Spondylitis',
  668: 'Spondylolisthesis',
  669: 'Spondylosis',
  670: 'Spontaneous Abortion',
  671: 'Sporotrichosis',
  672: 'Sprain or Strain',
  673: 'Stenosis of the Tear Duct',
  674: 'Stomach Cancer',
  675: 'Strep Throat',
  676: 'Stress Incontinence',
  677: 'Stricture of the Esophagus',
  678: 'Stroke',
  679: 'Stye',
  680: 'Subacute Thyroiditis',
  681: 'Subarachnoid Hemorrhage',
  682: 'Subconjunctival Hemorrhage',
  683: 'Subdural Hemorrhage',
  684: 'Substance-Related Mental Disorder',
  685: 'Syndrome of Inappropriate Secretion of ADH (SIADH)',
  686: 'Syphilis',
  687: 'Syringomyelia',
  688: 'Systemic Lupus Erythematosis (SLE)',
  689: 'Teething Syndrome',
  690: 'Temporary or Benign Blood in Urine',
  691: 'Temporomandibular Joint Disorder',
  692: 'Tendinitis',
  693: 'Tension Headache',
  694: 'Testicular Cancer',
  695: 'Testicular Disorder',
  696: 'Testicular Torsion',
  697: 'Thalassemia',
  698: 'Thoracic Aortic Aneurysm',
  699: 'Thoracic Outlet Syndrome',
  700: 'Threatened Pregnancy',
  701: 'Thrombocytopenia',
  702: 'Thrombophlebitis',
  703: 'Thyroid Cancer',
  704: 'Thyroid Disease',
  705: 'Thyroid Nodule',
  706: 'Tic (Movement) Disorder',
  707: 'Tietze Syndrome',
  708: 'Tinnitus of Unknown Cause',
  709: 'Tonsillar Hypertrophy',
  710: 'Tonsillitis',
  711: 'Tooth Abscess',
  712: 'Tooth Disorder',
  713: 'Torticollis',
  714: 'Tourette Syndrome',
  715: 'Toxic Multinodular Goiter',
  716: 'Toxoplasmosis',
  717: 'Tracheitis',
  718: 'Transient Ischemic Attack',
  719: 'Trichiasis',
  720: 'Trichinosis',
  721: 'Trichomonas Infection',
  722: 'Tricuspid Valve Disease',
  723: 'Trigeminal Neuralgia',
  724: 'Trigger Finger (Finger Disorder)',
  725: 'Tuberculosis',
  726: 'Tuberous Sclerosis',
  727: 'Turner Syndrome',
  728: 'Typhoid Fever',
  729: 'Ulcerative Colitis',
  730: 'Urethral Disorder',
  731: 'Urethral Stricture',
  732: 'Urethral Valves',
  733: 'Urethritis',
  734: 'Urge Incontinence',
  735: 'Urinary Tract Infection',
  736: 'Urinary Tract Obstruction',
  737: 'Uterine Atony',
  738: 'Uterine Cancer',
  739: 'Uterine Fibroids',
  740: 'Uveitis',
  741: 'VACTERL Syndrome',
  742: 'Vaginal Cyst',
  743: 'Vaginal Yeast Infection',
  744: 'Vaginismus',
  745: 'Vaginitis',
  746: 'Valley Fever',
  747: 'Varicocele of the Testicles',
  748: 'Varicose Veins',
  749: 'Vasculitis',
  750: 'Venous Insufficiency',
  751: 'Venous Thrombosis',
  752: 'Ventricular Fibrillation',
  753: 'Ventricular Septal Defect',
  754: 'Verruca',
  755: 'Vertigo',
  756: 'Vestibular Neuronitis',
  757: 'Vitamin B12 Deficiency',
  758: 'Vitamin D Deficiency',
  759: 'Vitiligo',
  760: 'Vocal Cord Disorder',
  761: 'Vocal Cord Polyp',
  762: 'Vocal Cord Paralysis',
  763: 'Vomiting of Unknown Cause',
  764: 'Von Willebrand Disease',
  765: 'Vulvar Cancer',
  766: 'Vulvar Disorder',
  767: 'Vulvovaginitis',
  768: 'Warts',
  769: 'Wegener Granulomatosis',
  770: 'Wernicke Encephalopathy',
  771: 'West Nile Virus Infection',
  772: 'Wilson Disease'
};

module.exports = DISEASE_MAP; 