version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - PORT=5000
      - HOST=0.0.0.0
    networks:
      - app-network

  frontend:
    build: 
      context: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

# version: '3.8'
# services:
#   frontend:
#     build: ./frontend
#     ports:
#       - "80:80"
#     depends_on:
#       - backend
#     environment:
#       - VITE_API_URL=http://localhost/api

#   backend:
#     build: ./backend
#     ports:
#       - "5000:5000"
#     environment:
#       - NODE_ENV=production
#       - PORT=5000
#       - HOST=0.0.0.0 