version: '3.8'

services:
  frontend:
    image: shivakumarreddy1/disease-detection-frontend:__TAG__
    ports:
      - "80:80"    # ✅ Listen on host port 80 for public access
    environment:
      - VITE_API_URL=http://backend:5000/api  # if used by your frontend

  backend:
    image: shivakumarreddy1/disease-detection-backend:__TAG__
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - PORT=5000
      - HOST=0.0.0.0
